### ISSUE TITLE
Support for hex colors.

### ISSUE THREAD

**Issue by PastosBaran** [HexedHero/CitizensCMD#1]
The plugin can support hex codes. For 1.16 and above I tried to try this with placeholders but the color is broken.

https://prnt.sc/g89xOMtAo-hU
https://prnt.sc/De-ewaJMWTnF

It would be great if this plugin supports hex codes.

**Comment by HexedHero** [comment]
You can use MiniMessage (recommended) and use the <#FFFFFF> format or use the legacy &x&f&f&f&f&f&f format.

**Comment by PastosBaran** [comment]
https://prnt.sc/sJR78p5skzKi 
https://prnt.sc/NI5YGlI-1HzK

not working. :(

**Comment by PastosBaran** [comment]
saves.yml

https://prnt.sc/epHQ4jvOQbcw

**Comment by PastosBaran** [comment]
also in the other format(&x.....) the color that should be shown green is shown as orange.

https://prnt.sc/gV_3mSGYDkkh

saves.yml

https://prnt.sc/L6D0FONLVgFZ

**Comment by HexedHero** [comment]
You have to enable MiniMessage in your config.

**Comment by PastosBaran** [comment]
oww, I didn't think there was a config setting related to this. Thank you for your help.
