### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by BestMark** [HexedHero/CitizensCMD#11]
![image](https://github.com/HexedHero/CitizensCMD/assets/18399104/aaa048a9-47a0-4b10-80f2-1f80207d94df)

![image](https://github.com/HexedHero/CitizensCMD/assets/18399104/d20ffa71-6d38-46bc-8fe2-04bd7d1ba43d)

**Comment by BestMark** [comment]
![image](https://github.com/HexedHero/CitizensCMD/assets/18399104/dbedb48d-fa8e-4869-99d2-65c51d204b87)
40KB

**Comment by BestMark** [comment]
Can you add some option to disable cooldown? I set default cooldown in my config to 0, but it still works...

**Comment by HexedHero** [comment]
Fixed by 9e04abd9c458fd0154482f453a87af789d709420.
