### ISSUE TITLE
Stop using EventPriority.MONITOR

### ISSUE THREAD

**Issue by Real6dq** [HexedHero/CitizensCMD#13]
![image](https://github.com/HexedHero/CitizensCMD/assets/104909470/425e579f-9832-4edb-aef6-cd63c3d7576c)
Please, remove the monitor from every single listener.
Replace it with anything else, asap, this will crash the hell out of your server, a new crashing method.
Monitor cannot be cancelled, so no point of the ignoreCancelled.

**Comment by HexedHero** [comment]
> Monitor cannot be cancelled, so no point of the ignoreCancelled.

That is not how Montior works. It looks like your crash is from a player spamming /pv which is not from CitizensCMD and would happen just by spamming the command (Unless you have command spam protection) which you'll need to add a cooldown on the NPC.
