### ISSUE TITLE
The data sometimes lost

### ISSUE THREAD

**Issue by JFJiuBan** [HexedHero/CitizensCMD#2]
I use the latest version - 2.6.2 and Paper(1.18.2). The save.yml may sometimes lose some data. It is randomly! No any information on the backstage.

**Comment by HexedHero** [comment]
This seems to be have been a bug for the longest time, I've personally had it happen once when I had to restore the file from a backup but it only happened once when my Citizens didn't load. I haven't looked into the data saving part of the plugin yet.

**Comment by JFJiuBan** [comment]
Actually, it happens to me many times recent days. Like 3 times a day(24h). If that is ok, plz help me check the problem, I try to restore the data everytime I done it. I can't look the backstage everytime, and can't reload the backup everytime. By the way, my English is not well, plz forgive the grammar and some inappropriate words.

**Comment by HexedHero** [comment]
Is your Citizens failing to load? The only reason it deletes data is when the NPC remove event gets called from Citizens.

**Comment by HexedHero** [comment]
Of course, unloading Citizens with Plugman will cause this. Don't use plugman for anything full stop, there is no way to fix this, CitizensCMD sees that Citizens is removing NPC's so it removes the data.
