### ISSUE TITLE
Recorded dialogs do not load on server restart

### ISSUE THREAD

**Issue by Cymerline84** [HexedHero/CitizensCMD#3]
**Describe the bug**
Recorded dialogs do not load on server restart.
It takes every reboot that I type /npcmd reload for the dialogs to load

**Screenshots**
Link to screens

https://ibb.co/wrNT6rd
https://ibb.co/M6L6qv6
https://ibb.co/qCT03GV
https://ibb.co/sK2ftSv

**Versions (please complete the following information):**
 - Citizens version v2.04.29 Premium version
 - Spigot version last version
 - CitizensCMD 2.6.2
- Java version 17
- Paper version 1.18.2

**Comment by HexedHero** [comment]
I can't seem to reproduce this

**Comment by HexedHero** [comment]
Closing as we haven't heard back. Feel free to reopen if it's still an issue.
