### ISSUE TITLE
Citizenscmd can't find Citizens.jar

### ISSUE THREAD

**Issue by Ignius14** [HexedHero/CitizensCMD#4]
https://mclo.gs/0sA4KZX (it will be easier)

So yeah my problem is this idk what to do tho

**Comment by HexedHero** [comment]
Your other plugins cannot find Citizens too.
[17:25:52] [Server thread/ERROR]: [BeautyQuests] No NPC plugin installed - please install Citizens or znpcs
You need to fix your mass amount of startup errors to actually have a clean startup.
