### ISSUE TITLE
Error  

### ISSUE THREAD

**Issue by AmziXzYT** [HexedHero/CitizensCMD#7]
Plugin CitizensCMD v2.6.7 tried to register permission 'citizenscmd.remove' but it's already registered
java.lang.IllegalArgumentException: The permission citizenscmd.remove is already defined!

Please help fix this :(

**Comment by AmziXzYT** [comment]
Im using paper 1.8.8

**Comment by HexedHero** [comment]
It seems you reloaded the server or used PlugMan to reload the plugin.
